### ISSUE TITLE
Const errors in Processing Streaming PCD

### ISSUE THREAD

**Issue by swwelch** [awbrown90/SensorFusionHighway#1]
In the Processing Streaming PCD markdown, the first code snippet suggests the following function signature:
```
void cityBlock(pcl::visualization::PCLVisualizer::Ptr& viewer, ProcessPointClouds<pcl::PointXYZI>* pointProcessorI, const pcl::PointCloud<pcl::PointXYZI>::Ptr& inputCloud)
```
Adding `const` here causes compile-time errors for me that can't be fixed without changing other code. If we want to use `const`, it might be a good idea to tell students what else to change to make this work.

**Comment by awbrown90** [comment]
I see, yes it would give complile-time errors if we try to change inputCloud at all, which would be my guess as to what might be happening.  In my code I was just using inputCloud as an argument, but if you tried to directly reassign it, that would throw an error. I would be curious to hear if that is what is causing the error. If it is then we can add that information to the course document.
